author: 
  name: "Lars Vilhuber"
  homepage: "https://your-homepage.com"

github:
  url: "https://github.com/larsvilhuber/reproducibility-for-llm/"

format: 
  revealjs:
    baseurl: https://larsvilhuber.github.io/reproducibility-for-llm/presentation/
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    theme: [night, style.css]
    self_contained: false
    reveal_options:
        slideNumber: true
        previewLinks: false
        chalkboard:
          theme: chalkboard
          toggleNotesButton: true
    reveal_plugins: ["chalkboard"]

