author: 
  name: "Lars Vilhuber"
  homepage: "https://lars.vilhuber.com"

format:
  revealjs:
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    theme: [night, style.css]
    embed-resources: false
    slide-number: true
    preview-links: false
    chalkboard:
      theme: chalkboard

